name: Update Version Files

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version file
        run: |
          if echo "${{ env.VERSION }}" | grep -q "_beta"; then
            echo "${{ env.VERSION }}" > beta_version.txt
          else
            echo "${{ env.VERSION }}" > stable_version.txt
          fi

      - name: Commit and push changes
        run: |
          git add *_version.txt
          git commit -m "Update version file for ${{ env.VERSION }}" || echo "No changes to commit"
          git push
